export const flavours = [
  { id: 1, label: "Orange" },
  { id: 2, label: "Lemon" },
  { id: 3, label: "Bergamot" },
  { id: 4, label: "Red Apple" },
  { id: 5, label: "Cherry" },
  { id: 6, label: "Strawberry" },
  { id: 7, label: "Blueberry" },
  { id: 8, label: "Peach" },
  { id: 9, label: "Mango" },
  { id: 10, label: "Pineapple" },
  { id: 11, label: "Almond" },
  { id: 12, label: "Hazelnut" },
  { id: 13, label: "Walnut" },
  { id: 14, label: "Milk Chocolate" },
  { id: 15, label: "Dark Chocolate" },
  { id: 16, label: "Caramel" },
  { id: 17, label: "Honey" },
  { id: 18, label: "Brown Sugar" },
  { id: 19, label: "Vanilla" },
  { id: 20, label: "Toffee" },
  { id: 21, label: "Black Tea" },
  { id: 22, label: "Jasmine" },
  { id: 23, label: "Floral" },
  { id: 24, label: "Lavender" },
  { id: 25, label: "Cinnamon" },
  { id: 26, label: "Clove" },
  { id: 27, label: "Molasses" },
  { id: 28, label: "Cocoa" },
  { id: 29, label: "Raisin" },
  { id: 30, label: "Stone Fruit" },
];
